### ISSUE TITLE
Default "there is an opposing party", with some handling of "in re" cases

### ISSUE THREAD

**Issue by suffolklitlab-issues** [IllinoisLegalAidOnline/docassemble-IlFeeWaiver#10]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `is there an opposing party?`
language | If I am the defendant/respondent, there will have to be a plaintiff/petitioner in this case, so I think we can skip this question.
Other information | 
Variable being sought | `other_parties.there_are_any`
Package version | `1.1.4`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | mnewsted

**Comment by nonprofittechy** [comment]
@mnewsted what if the case is an "In re" / "In the matter of"?

Maybe there's a way to phrase that more clearly for that situation
