### ISSUE TITLE
Add OBO language on birth year question

### ISSUE THREAD

**Issue by suffolklitlab-issues** [IllinoisLegalAidOnline/docassemble-IlFeeWaiver#13]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `birth year`
language | Including the name of OBO in this what year were you born would be very helpful. Also, I think this needs a validation check. if it is OBO a minor, it should be <18. If it is OBO an adult or if the user is the filer, it should be 18+.
Other information | 
Variable being sought | `users[0].birth_year`
Package version | `1.1.4`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | mnewsted

**Comment by nonprofittechy** [comment]
Fixed in https://github.com/SuffolkLITLab/docassemble-IlFeeWaiver/commit/3199b8254e6599c087ab9c4ba275644a369f270c
