### ISSUE TITLE
add /s/ signature?

### ISSUE THREAD

**Issue by suffolklitlab-issues** [IllinoisLegalAidOnline/docassemble-IlFeeWaiver#15]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `signature choice`
language | In IL courts, you can e-sign by typing /s/ Signature. Maybe replace this with a question, do you want to e-sign your forms? (See Appearance)
Other information | 
Variable being sought | `saw_signature_choice`
Package version | `1.1.4`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | mnewsted

**Comment by nonprofittechy** [comment]
@mnewsted is there a good reason to have people use /s/ rather than a digital signature? That's not easy to do w/ PDF filling as it exists now.

**Comment by mnewsted** [comment]
@nonprofittechy  This is how the statewide forms implement the IL Sup Ct rule. Actually, I thought this was pretty easy to implement. In the Appearance and all other programs, we  just ask a Y/N question if they want to include an e-signature. If yes, we just put the user's name in the field (it already has /s/ on the form). Maybe I'm not understanding the issue.

**Comment by nonprofittechy** [comment]
The form  can either hold a text field or digital signature, not both in the same place. There is probably a workaround like adding a transparent layer on top of the field in the same place, but I haven't tried before.
