### ISSUE TITLE
More places to add OBO

### ISSUE THREAD

**Issue by suffolklitlab-issues** [IllinoisLegalAidOnline/docassemble-IlFeeWaiver#3]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Who is filing this fee waiver`
enhancement | Could we move the how are you related to the filer question to after you enter the name of the person you are filing on behalf of? That way we can ask, "how are you related to NAME?" in a place more directly connected with the person seeking the fee waiver.
Other information | 
Variable being sought | `filing_basis`
Package version | `1.1.4`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | mnewsted

**Comment by nonprofittechy** [comment]
@mnewsted I'm going to roll in some of these changes to make the text responsive to you/on behalf of.

I will commit to Main by the end of the day so you should do a new pull at some point so you don't duplicate effort.
