### ISSUE TITLE
Email needs to be required on the contact methods page (only if they have one)

### ISSUE THREAD

**Issue by suffolklitlab-issues** [IllinoisLegalAidOnline/docassemble-IlFeeWaiver#4]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `your contact information`
enhancement | In Illinois, phone numbers are optional. Since there is only 1 phone number field, maybe we don't need to distinguish between mobile & other phone number.

Also, email is required, if the user has one. We have developed questions and logic for how to address this. Something like this (but it can be shortened): The court clerk can send you important information about your court case by email. If you do not have an email address, you will be notified by US mail.
Do you have an email address?
If they answer yes, we include this text: This email address will appear on your court forms. Be sure to check this email daily, otherwise you may miss important information about your case.
Other information | 
Variable being sought | `users[0].email`
Package version | `1.1.4`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | mnewsted

**Comment by nonprofittechy** [comment]
Remove the extra fields on the "contact methods" page, at least for now. We only want phone number and email.
