### ISSUE TITLE
Change order of the "fill in the rest of the information" prompt

### ISSUE THREAD

**Issue by suffolklitlab-issues** [IllinoisLegalAidOnline/docassemble-IlFeeWaiver#5]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Who is filing this fee waiver`
language | "Okay. List your name below. Fill in the rest of the information on this website as if you are the person who you are helping."
This text is helpful, but I think it should appear after entering phone number & email & address to avoid any confusion about whether it is for the user or the person OBO.
Other information | 
Variable being sought | `filing_basis`
Package version | `1.1.4`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | mnewsted

**Comment by nonprofittechy** [comment]
Given fixes to make language more adaptive, I think we can actually just remove that help text now.
