### ISSUE TITLE
Rephrase "Do you receive any benefits" question to refer to OBO user/form user

### ISSUE THREAD

**Issue by suffolklitlab-issues** [IllinoisLegalAidOnline/docassemble-IlFeeWaiver#6]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Do you receive any benefits`
language | Maybe we could use the OBO name on all the subsequent questions about whether it is You or OBO. For example, Do you currently receive public benefits? vs. Does NAME currently receive public benefits? I realize this contradicts the warning in the earlier question, but I think it would be easy enough to implement this. If done throughout the program, we could maybe even do away with the warning? Maybe not MVP.
Other information | 
Variable being sought | `user_benefits`
Package version | `1.1.4`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | mnewsted

**Comment by nonprofittechy** [comment]
@mnewsted LMK if you need help adding this dynamic language
